name: Test on demand

on:  
  workflow_dispatch:
    inputs:
      target:
        description: 'HOST to target tests (default: beta.hydroshare.org).'
        default: 'beta.hydroshare.org'

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.9]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
        pip install .
    - name: Run Tests against target = ${{ github.event.inputs.target }}
      env:
        HYDRO_USERNAME: ${{ secrets.HYDRO_USERNAME }}
        HYDRO_PASSWORD: ${{ secrets.HYDRO_PASSWORD }}
        HYDRO_HOST: ${{ github.event.inputs.target }}
      run: |
        make test-cov
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.11
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
